---
- name: include os specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - default.yml
      paths:
        - installer



- include: 'installer/apt.yml'
  when: docker_installer == 'apt'

- include: 'installer/pacman.yml'
  when: docker_installer == 'pacman'

- include: 'installer/yum.yml'
  when: docker_installer == 'yum'

- include: 'installer/zypper.yml'
  when: docker_installer == 'zypper'

- include: 'installer/default.yml'
  when: docker_installer == 'default'



- name: install docker-py
  pip:
    name: docker-py
    state: present
    executable: pip2

- name: ensure "docker" group present
  group:
    name: docker
    state: present
    system: yes

- name: add users into "docker"
  user:
    append: yes
    groups: docker
    state: present
    name: '{{ item }}'
  with_items: docker_users or []
