---
- name: include os specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - default.yml
      paths:
        - ../vars/installer



- include: 'installer/pacman.yml'
  when: docker_installer == 'pacman'

- include: 'installer/default.yml'
  when: docker_installer == 'default'
